"""add_receipt_items_table

Revision ID: aea5fadf0609
Revises: 133321c4ec16
Create Date: 2026-02-18 15:51:44.882473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aea5fadf0609'
down_revision: Union[str, Sequence[str], None] = '133321c4ec16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipt_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('receipt_batch_id', sa.String(length=36), nullable=False),
    sa.Column('raw_name', sa.String(length=255), nullable=False, comment='Original name from receipt'),
    sa.Column('normalized_name', sa.String(length=255), nullable=False, comment='Cleaned name for matching'),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False, comment='Price per unit'),
    sa.Column('total_price', sa.Float(), nullable=False, comment='quantity * unit_price (pre-computed for aggregation)'),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('store', sa.String(length=100), nullable=False, comment="Store name (e.g., 'Walmart', 'Kroger')"),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=False, comment='Date of purchase'),
    sa.Column('matched_pantry_item_id', sa.Integer(), nullable=True, comment='Links to pantry item if matched during ingestion'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['matched_pantry_item_id'], ['pantry_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_items_category'), 'receipt_items', ['category'], unique=False)
    op.create_index(op.f('ix_receipt_items_normalized_name'), 'receipt_items', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_receipt_items_receipt_batch_id'), 'receipt_items', ['receipt_batch_id'], unique=False)
    op.create_index(op.f('ix_receipt_items_store'), 'receipt_items', ['store'], unique=False)
    op.create_index(op.f('ix_receipt_items_user_id'), 'receipt_items', ['user_id'], unique=False)
    op.create_index('ix_receipt_name_store', 'receipt_items', ['normalized_name', 'store'], unique=False)
    op.create_index('ix_receipt_user_category', 'receipt_items', ['user_id', 'category'], unique=False)
    op.create_index('ix_receipt_user_date', 'receipt_items', ['user_id', 'purchase_date'], unique=False)
    op.create_index('ix_receipt_user_store', 'receipt_items', ['user_id', 'store'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_receipt_user_store', table_name='receipt_items')
    op.drop_index('ix_receipt_user_date', table_name='receipt_items')
    op.drop_index('ix_receipt_user_category', table_name='receipt_items')
    op.drop_index('ix_receipt_name_store', table_name='receipt_items')
    op.drop_index(op.f('ix_receipt_items_user_id'), table_name='receipt_items')
    op.drop_index(op.f('ix_receipt_items_store'), table_name='receipt_items')
    op.drop_index(op.f('ix_receipt_items_receipt_batch_id'), table_name='receipt_items')
    op.drop_index(op.f('ix_receipt_items_normalized_name'), table_name='receipt_items')
    op.drop_index(op.f('ix_receipt_items_category'), table_name='receipt_items')
    op.drop_table('receipt_items')
    # ### end Alembic commands ###
